### ISSUE TITLE
Proxy Service and Artifacts

### ISSUE THREAD

**Issue by wangdemon** [agafon0ff/SimpleRemoteDesktop#4]
I have two questions. (1) When my two computers A and B are in the LAN, computer A setup SimpleRemoteDesktop.exe Computer B can remotely control computer A by inputting the corresponding web address in the browser. But the desktop displayed of Computer B on the browser page has artifacts, especially when the mouse drags the window, the artifacts are more serious. (2)I don't know how to use it RemoteDesktopProxy.exe. I don't know how to use the proxy service. Can you write an operation instruction document.

**Comment by agafon0ff** [comment]
1) This version of the SDR is very crude and has display artifacts, and also works quite slowly. (Since this project is developed as an example of desktop management) It is planned to refine this and other problems later.
2) There are "config.ini" configuration files to configure the SimpleRemoteDesktop and the RemoteDesktopProxy:

[REMOTE_DESKTOP]
filesPath=:/res/
login=MyLogin
name=MyComputerName
pass=MyPassword
portHttp=8080
portWeb=8081
proxyHost=ws://127.0.0.1:8082
proxyLogin=ProxyLogin
proxyPass=ProxyPassword

[REMOTE_DESKTOP_PROXY]
filesPath=:/res
login=ProxyLogin
pass=ProxyPassword
portHttp=8080
portWebClient=8081
portWebDesktop=8082
